logging:
  level:
    com.ms.email: TRACE

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_GMAIL}
    password: ${PASSWORD_GMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    mode: HTML

  rabbitmq:
    addresses: ${RABBITMQ_URL}
    queues:
      email: ${RABBITMQ_QUEUE_EMAIL}
      welcome: ${RABBITMQ_QUEUE_WELCOME}
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
